gText_Birch_Welcome::
	.string "{COLOR BLUE}Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of {COLOR RED}Pokémon{COLOR BLUE}!\p"
	.string "My name is {COLOR RED}Birch{COLOR BLUE}.\p"
	.string "But everyone calls me the {COLOR RED}Pokémon\n"
	.string "Professor{COLOR BLUE}.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "{COLOR BLUE}This is what we call a {COLOR RED}Pokémon{COLOR BLUE}.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "{COLOR BLUE}This world is widely inhabited by\n"
	.string "creatures known as {COLOR RED}Pokémon{COLOR BLUE}.\p"
	.string "We humans live alongside {COLOR RED}Pokémon{COLOR BLUE},\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about {COLOR RED}Pokémon{COLOR BLUE}.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding {COLOR RED}Pokémon{COLOR BLUE}.\p"
	.string "To unravel {COLOR RED}Pokémon{COLOR BLUE} mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "{COLOR BLUE}And you are?$"

gText_Birch_BoyOrGirl::
	.string "{COLOR BLUE}Are you a {COLOR LIGHT_GREEN}cool {COLOR BLUE}or\n"
	.string "a {COLOR LIGHT_GREEN}cute {COLOR BLUE}trainer?$"

gText_Birch_WhatsYourName::
	.string "{COLOR BLUE}All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "{COLOR BLUE}So it's {COLOR LIGHT_GREEN}{PLAYER}{KUN}{COLOR BLUE}?$"

gText_Birch_YourePlayer::
	.string "{COLOR BLUE}Ah, okay!\p"
	.string "You're {COLOR LIGHT_GREEN}{PLAYER}{KUN} {COLOR BLUE}who's moving to my\n"
	.string "hometown of {COLOR RED}Littleroot{COLOR BLUE}.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{COLOR BLUE}All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of {COLOR RED}Pokémon{COLOR BLUE} where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my {COLOR RED}Pokémon Lab{COLOR BLUE}.\p"
	.string "$"
