gText_Birch_Welcome::
	.string "{COLOR GREEN}Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of {COLOR DYNAMIC_COLOR4}Pokémon{COLOR GREEN}!\p"
	.string "My name is {COLOR RED}Birch{COLOR GREEN}.\p"
	.string "But everyone calls me the {COLOR RED}Pokémon\n"
	.string "Professor{COLOR GREEN}.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "{COLOR GREEN}This is what we call a “{COLOR DYNAMIC_COLOR4}Pokémon{COLOR GREEN}.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "{COLOR GREEN}This world is widely inhabited by\n"
	.string "creatures known as {COLOR DYNAMIC_COLOR4}Pokémon{COLOR GREEN}.\p"
	.string "We humans live alongside {COLOR DYNAMIC_COLOR4}Pokémon{COLOR GREEN},\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about {COLOR DYNAMIC_COLOR4}Pokémon{COLOR GREEN}.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding {COLOR DYNAMIC_COLOR4}Pokémon{COLOR GREEN}.\p"
	.string "To unravel {COLOR DYNAMIC_COLOR4}Pokémon{COLOR GREEN} mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "{COLOR GREEN}And you are?$"

gText_Birch_BoyOrGirl::
	.string "{COLOR GREEN}Are you a {COLOR DYNAMIC_COLOR5}cool {COLOR GREEN}or\n"
	.string "a {COLOR DYNAMIC_COLOR5}cute {COLOR GREEN}trainer?$"

gText_Birch_WhatsYourName::
	.string "{COLOR GREEN}All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "{COLOR GREEN}So it's {COLOR DYNAMIC_COLOR5}{PLAYER}{KUN}{COLOR GREEN}?$"

gText_Birch_YourePlayer::
	.string "{COLOR GREEN}Ah, okay!\p"
	.string "You're {COLOR DYNAMIC_COLOR5}{PLAYER}{KUN} {COLOR GREEN}who's moving to my\n"
	.string "hometown of {COLOR RED}Littleroot{COLOR GREEN}.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{COLOR GREEN}All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of {COLOR DYNAMIC_COLOR4}Pokémon{COLOR GREEN} where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my {COLOR RED}Pokémon Lab{COLOR GREEN}.\p"
	.string "$"
